Add a simple block hud.
FoxStudios/FoxClient pull request #30
Opened 2023-07-02 09:53 UTC by Flustix

Adds a HUD element which shows what block you're currently looking at. Also has fade and resize animations.

![image](https://github.com/FoxStudios/FoxClient/assets/65369281/27f5e782-a76f-451e-a011-a0f67f52fe66)

Known Issues:
- The rendered block doesn't fade out.

2023-07-02 14:55 UTC, RoootTheFox commented
looks neat on first glance, gonna do a proper review<img src="https://cdn.discordapp.com/emojis/869694774209310751.webp?size=128&quality=lossless" alt=":PepeThumbsUp:" width="24" height="24">

2023-07-02 15:20 UTC, RoootTheFox commented
I'm not a big fan of the rounding on the block HUD, I'd either disable it there or make that configurable.

2023-07-03 12:53 UTC, Flustix commented
Fixed the block not fading in by simply replacing the fade animation

2023-07-29 11:39 UTC, RoootTheFox commented on src/main/java/net/foxes4life/foxclient/gui/BlockHud.java
> +        String translationKey = block.getTranslationKey();
seems like an unused variable assignment, could be directly put into the translatable method call next line

2023-07-29 11:43 UTC, RoootTheFox commented on src/main/java/net/foxes4life/foxclient/gui/BlockHud.java
> +        if (camera == null) return null;
this would look better if those were merged into one if statement

2023-07-29 11:53 UTC, RoootTheFox commented
Animation speed is linked to FPS - at ~500+ FPS you don't even notice that there's an animation in the first place.
likewise, at very low framerate the animation would be very slow too
this also causes things like this: 
![image](https://github.com/FoxStudios/FoxClient/assets/78933889/dbccc1fe-2fe1-4fb5-9f3b-5b70c8a99c39)

2023-07-29 12:20 UTC, RoootTheFox requested changes
looks good, but there are some issues and the code could be cleaned up a little

2023-07-29 12:20 UTC, RoootTheFox commented on src/main/java/net/foxes4life/foxclient/gui/BlockHud.java
> +import net.minecraft.client.network.ClientPlayerEntity;
unused imports

2023-07-29 12:20 UTC, RoootTheFox commented on src/main/java/net/foxes4life/foxclient/gui/BlockHud.java
> +import net.minecraft.client.render.model.json.ModelTransformationMode;
unused imports

2023-07-29 12:20 UTC, RoootTheFox commented on src/main/java/net/foxes4life/foxclient/gui/BlockHud.java
> +import net.minecraft.entity.player.PlayerEntity;
unused import

2023-07-29 12:20 UTC, RoootTheFox commented on src/main/java/net/foxes4life/foxclient/gui/BlockHud.java
> +import com.mojang.blaze3d.systems.RenderSystem;
unused import

2023-07-29 12:20 UTC, RoootTheFox commented on src/main/java/net/foxes4life/foxclient/gui/BlockHud.java
> +        else {
style: please put `else` on the same line as the `}` belonging to the original if statement

2023-07-29 12:20 UTC, RoootTheFox commented on src/main/java/net/foxes4life/foxclient/gui/BlockHud.java
> +        else y = goalY;
style: not a fan of omitting curly braces in an if-else statement, makes it harder to read the code

2023-07-29 12:20 UTC, RoootTheFox commented on src/main/java/net/foxes4life/foxclient/gui/BlockHud.java
> +        MutableText text = TextUtils.translatable(translationKey);
unused variable assignment, `block.getTranslationKey()` should be inside the method call for `TextUtils.translatable()`

2023-07-29 12:20 UTC, RoootTheFox commented on src/main/java/net/foxes4life/foxclient/gui/BlockHud.java
> +        else width = w;
same as before, please avoid omitting curly braces for if-else statements

2023-07-29 12:20 UTC, RoootTheFox commented on src/main/java/net/foxes4life/foxclient/gui/BlockHud.java
> +        if (interactionManager == null) return null;
putting these below each other and merging them in a single if statement would look better

2023-07-29 12:20 UTC, RoootTheFox commented on src/main/java/net/foxes4life/foxclient/gui/BlockHud.java
> +        Vec3d startVector = camera.getCameraPosVec(client.getTickDelta());
I would put the value of `client.getTickDelta()` in a variable to avoid calling it twice

2023-07-29 12:44 UTC, RoootTheFox commented
> Animation speed is linked to FPS - at ~500+ FPS you don't even notice that there's an animation in the first place. likewise, at very low framerate the animation would be very slow too this also causes things like this: ![image](https://user-images.githubusercontent.com/78933889/256981098-dbccc1fe-2fe1-4fb5-9f3b-5b70c8a99c39.png)

video showing the issue:

[2023-07-29 14-29-23.webm](https://github.com/FoxStudios/FoxClient/assets/78933889/0986f23b-fa88-4cf6-b9bb-276c462a66c1)

2023-08-03 19:55 UTC, RoootTheFox commented on src/main/java/net/foxes4life/foxclient/gui/BlockHud.java
> +//        context.drawText(client.textRenderer, "Draw delta: " + (int)delta + "ms", 10, 10, 0xFFFFFF, false);
is this supposed to be still here?

2023-08-03 19:56 UTC, RoootTheFox approved these changes

2023-08-03 19:56 UTC, RoootTheFox commented
looks good, lgtm

2023-08-03 19:57 UTC, merged